### ISSUE TITLE
Inference questions

### ISSUE THREAD

**Issue by Jerry7j** [JDSobek/MedYOLO#8]
Dear Sobek, 

Hi, maybe you are in the Christmas holiday. Hope you have a fun time!

For the infer part, I have two questions.

1.
I find without the original project directory, the model load will has this problem.

This is the directory same as the original project.
![image](https://github.com/JDSobek/MedYOLO/assets/51701056/7de54983-8bea-4ee1-bfc0-cbdade522dca)

This is the changed directory. Without the models/common.py
![image](https://github.com/JDSobek/MedYOLO/assets/51701056/4835c85b-f615-4f83-bc8e-809fd746b650)

But if I don't set the same directory as the original project directory, it will bring this:
https://github.com/JDSobek/MedYOLO/blob/e734b9afefd0341a490e2179eba98221d40bce64/models3D/model.py#L53
![image](https://github.com/JDSobek/MedYOLO/assets/51701056/05e44e39-d2cf-4602-867b-2223cbc6d898)

I have integrated this common.py content in local .py file, but it always find other module.
![image](https://github.com/JDSobek/MedYOLO/assets/51701056/cd8dc965-05c5-491d-8310-727977c61b05)

My purpose is to make the infer part independently.

2.
How to accelerate the infer speed?
For the one example, this data: 510 * 381 * 446 with spacing about 0.5mm.  yolom model with half(True) FP16.

Here is the time log,
Load model ----- 0.778  s
WARNING: --img-size [350] must be multiple of max stride 32, updating to [352]
Load data ----- 0.871  s
sitk.Read ----- 0.772  s  (I use the SimpleITK to read the origin again for using TransformIndexToPhysicalPoint method)
all ----- 3.87  s

Do you think change the origin data's spacing for inference will accelerate? I worry it will generate a bad result or no result.

**Comment by JDSobek** [comment]
Thank you.

1. YOLOv5 code (and thus MedYOLO, since it's constructed to look as close as possible to it) makes many calls between its different files.  Sometimes those imports only happen when a particular function is run, and it will take a long time to trace all of the functions until you sort out all of the dependencies.

For that reason, I don't recommend trying to make any of the scripts stand-alone versions of themselves because you're either going to end up needing to put a very big chunk of the repository into that script or you're going to end up with a lot of redundant code.  Either situation will make it much harder to understand the new code.  I would particularly recommend not changing the basic YOLOv5 code that I left in, that code is typically very fundamental and often referenced in many places.

If you really, really want to try and make a stand-alone inference script, I suggest you take a good IDE and have it tell you everywhere the code you want to move is referenced, and then tell you everywhere the functions that reference that code are referenced, etc.  It's probably not going to be worth investing your time in, though.

2. The biggest problem with speed is that every NIfTI file is equivalent to dozens or hundreds of images which need to be loaded into memory, sent to the GPU, transformed, etc. and that makes them have a very large overhead compared to photographs.  There might be a clever way to speed things up more if you have a good handle on C++ and how NIfTI data is stored in the files, but it's already as baremetal as I could make it with just Python and nibabel.

Making your files smaller would probably speed up loading, (510, 381, 446) is a pretty large number of slices and inference will reshape it to (352, 352, 352) anyway, but you will probably get a bad result if your inference data leaves the training data's domain.  Of course, the time you spend reshaping your inference data before feeding it to the MedYOLO model is likely going to take longer than the amount of time you save running MedYOLO on the smaller files.

I guess the short answer is it's as fast as I could make it and I'm not aware of a faster competitor (whose hypothetical code I'd gladly try to emulate...).  If you come up with a good way to make the inference process faster, let me know... I don't think doing anything to your data before running the script is going to be helpful speed-wise, though, just because of the added overhead processing time.

**Comment by Jerry7j** [comment]
Thank you for the detail suggestions!

Yeah. It really need time to integrate all of the dependencies. So, I keep the original project structure now. 

About the inference speed. NIfTI file like a hundreds of images. Actually the smaller files has a better speed, but the most situation is large data like (512, 512, 512). Because I envisage the roi area will be finded in a short time, then send the roi to a seg model, to save more time for seg. MedYOLO has achieved amazing result and high speed. I'm making a large data for a new training. 

I have tried to resample the data's spacing, it has a similar result with the original data. It also add a resample time. It seems resampled data has a better inference speed, but the whole time has more than the original data. Due to the normalized center and length，it also has a easy way to transfer the index point to physical point.
